### ISSUE TITLE
Discord no longer getting rich presence.

### ISSUE THREAD

**Issue by RadicalZoey** [RyadaProductions/RyaRpc#3]
Discord recognized the rich presence the first time right after RyaRpc installation, but after having closed it, and closing the game. The next time RyaRpc launches; Discord will no longer recognize the rich presence. RyaRpc was getting information from CS:GO but discord could not get the information from the app.

**Comment by RyadaProductions** [comment]
This was caused by an outdated version of the discord-rpc.dll i have updated this and it should not be reproducable anymore
